if window?
  {parse} = require './parser'
else
  {parse} = require '../lib/parser'

ErrorReporter = require 'error-reporter'


# A wrapper module for the parser generated by PEG.
#
# @note Provides a way to handle errors consistently regardless of if the error
# originated from PEG or was thrown manually as part the parsing expression for
# a rule.
#
module.exports =

  # Parse VFL to produce CCSS.
  #
  # @param source [String] A VFL expression.
  # @return [Array] The CCSS expressions equivalent to `source`.
  #
  parse: (source) ->
    results = null

    try
      results = parse source
    catch error
      errorReporter = new ErrorReporter source
      {message, line:lineNumber, column:columnNumber} = error
      errorReporter.reportError message, lineNumber, columnNumber

    return results
